version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up -d leetcode
      - run: docker-compose exec leetcode pnpm test

workflows:
  workflow:
    jobs:
      - test
