name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up --build --detach ci
      - run: docker compose exec --no-TTY ci pnpm lint
      - run: docker compose exec --no-TTY ci pnpm check
      - run: docker compose exec --no-TTY ci pnpm test
